config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'

  # Task 1
  resources :orders, only: :index
  get 'last_year', to: 'orders#within_last_year', as: :last_year_orders
  get '/api/last_year_by_months', to: 'api/orders#last_year_by_months', as: :last_year_by_months

  resources :preservations, only: %i[index show new create]
  resources :reports, only: %i[index]
  get '/get_report', to: 'reports#get_report', as: :get_report
end

app/models/preservation.rb
# == Schema Information
#
# Table name: preservations
#
#  id                        :bigint           not null, primary key
#  initial_file              :string
#  initial_file_link         :string           not null
#  logs                      :text
#  name_of_initial_file      :string
#  name_of_verification_file :string
#  preserved_file_link       :string
#  status                    :integer          default("pending"), not null
#  verification_file         :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#
class Preservation < ApplicationRecord
  validates :initial_file_link, presence: true, format: {
    with: %r{\A(http|https)://[\S]+\z},
    message: 'must be a valid URL starting with http:// or https://'
  }

  after_create :start_initial_download

  after_update :trigger_upload_service, if: -> { saved_change_to_status? && status == 'initial_attaching_finished' }

  # Планировалось, что данный коллбэк будет дергаться, чтобы повторно скачать файл уже с целевого "хранилища" File.io
  # т.е. протестиировать полностью метаданные + скачивание. Но т.к. сервис File.io после первого скачивания удаляет файл,
  # то пришлось отказаться от такой проверки. Альтернативный сервис не смог найти.
  # after_update :trigger_verification_mode, if: -> { saved_change_to_status? && status == 'preservation_finished' }

  # Поэтому заменено на более слабую проверку - просто по метаданным (без скачивания файла)
  after_update :trigger_verification_service, if: -> { saved_change_to_status? && status == 'preservation_finished' }

  ## Изначально скачиваемый файл
  mount_uploader :initial_file, InitialFileUploader

  ## Файл, скачиваемый уже для проверки корректности работы итоговой ссылки скачивания. Пришлось отказаться (см. коммент выше)
  # mount_uploader :verification_file, VerificationFileUploader

  enum :status, {
    pending: 0,
                  # Stage 1
                  downloading_in_progress: 1,
                  initial_download_failed: 2,
                  initial_attaching_failed: 3,
                  initial_attaching_finished: 4,
                  # Stage 2
                  uploading_in_progress: 5,
                  upload_failed: 6,
                  preservation_finished: 7,
                  # Stage 3
                  verification_in_progress: 8,
                  # verification_download_failed: 9,
                  # verification_attaching_failed: 10,
                  verification_failure: 11,
                  verification_finished: 12,
                  failed_unexpectedly: 13 # ,
    # deleted: 14
  }

  private

  def start_initial_download
    update(status: :downloading_in_progress)
    FileDownloadService.new(self, 'initial').call
  end

  def trigger_upload_service
    update(status: :uploading_in_progress)
    FileUploadService.new(self).call
  end

  # def trigger_verification_download
  #   update(status: :verification_in_progress)
  #   FileDownloadService.new(self, 'verification').call
  # end

  def trigger_verification_service
    update(status: :verification_in_progress)
    RemoteFileVerificationService.new(self).call
  end
end

app/controllers/preservations_controller.rb
class PreservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @preservations = Preservation.order(created_at: :desc)
  end

  def show
    @preservation = Preservation.find(params[:id])
  end

  def new
    @preservation = Preservation.new
  end

  def create
    @preservation = Preservation.new(preservation_params)
    if @preservation.save
      flash.now[:success] = 'Preservation successfully created'

      render turbo_stream: [
        turbo_stream.update('flash-messages', partial: 'shared/flash'),
        turbo_stream.update('form-errors', '')
      ]
    else
      flash.now[:alert] = 'Failed to create a new preservation.'

      render turbo_stream: [
        turbo_stream.update('flash-messages', partial: 'shared/flash'),
        turbo_stream.update('form-errors', partial: 'shared/errors', locals: { object: @preservation })
      ], status: :unprocessable_entity
    end
  end

  private

  def preservation_params
    params.require(:preservation).permit(:initial_file_link)
  end
end

app/views/preservations/_form.html.erb
<div id="form-errors"></div>

<%= form_with model: preservation do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label" style="width: 150px">
      <%= f.label :initial_file_link%>
    </div>
    <div>
      &nbsp;
    </div>
    <div class="col-sm-10">
      <%= f.text_field :initial_file_link, class: 'form-control', style: "width: 300px",
                        required: true, pattern: "https?://.+", title: "URL should start with http:// or https://" %>
    </div>
    <div>
      &nbsp;
    </div>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/preservations/index.html.erb
<div class="container container-widest">
  <span>
    <%= link_to 'New preservation', new_preservation_path, class: 'btn btn-primary btn-lg mb-3' %>
  <span>
</div>
<div class="container container-widest">
<% if @preservations.present? %>
  <h1 class="mb-4">All preservations</h1>
  <table class="table table-bordered table-striped mb-0" style="text-align: center">
    <thead>
        <tr>
          <th>ID</th>
          <th>Status</th>
          <th style="min-width: 400px">Initial file link</th>
          <th style="min-width: 400px">Preserved file link</th>
          <th>Logs</th>
          <th style="max-width: 100px">Temp.file (local)</th>
          <th>Created_at</th>
          <th>Actions</th>
        </tr>
    </thead>

    <tbody>
      <% @preservations.each do |preservation| %>
        <tr id="preservation_<%= preservation.id %>">
          <td><%= preservation.id %></td>
          <td><%= preservation.status %></td>
          <td style="min-width: 400px"><%= preservation.initial_file_link %></td>
          <td style="min-width: 400px"><%= preservation.preserved_file_link %></td>
          <td><%= preservation.logs.present? ? 'Check preservs page' : 'No logs' %></td>
          <td style="max-width: 100px">
            <%= preservation.initial_file.present? && preservation.name_of_initial_file.present? ?
                  link_to(preservation.name_of_initial_file, preservation.initial_file.url, download: preservation.name_of_initial_file) : 'нет' %>
          </td>

          <td><%= preservation.created_at %></td>
          <td style="text-align: center; justify-content: space-around;">
            <%= link_to 'Show', preservation_path(preservation), class: 'btn btn-success btn-lg mb-3' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1 class="mb-4">No preservations so far</h1>
<% end %>
</div>

app/views/preservations/new.html.erb
<div class="container container-wide">
<%= link_to 'Back to all preservations', preservations_path, class: 'btn btn-primary btn-lg mb-3' %>
</div>

<div class="container container-wide">
<h1 class="mb-4">New preservation</h1>
<%= render 'form', preservation: @preservation %>
</div>

app/views/preservations/show.html.erb
<div class="container container-widest">
<%= link_to 'Back to all preservations', preservations_path, class: 'btn btn-primary btn-lg mb-3' %>
<h1 class="mb-4">Preservation #<%= @preservation.id %></h1>
</div>
<div class="container container-widest">
  <table class="table table-bordered table-striped mb-0" style="text-align: center">
    <thead>
        <tr>
          <th>ID</th>
          <th>Status</th>
          <th style="min-width: 400px">Initial file link</th>
          <th style="min-width: 400px">Preserved file link</th>
          <th>Logs</th>
        </tr>
    </thead>

      <tbody>
        <tr>
          <td><%= @preservation.id %></td>
          <td><%= @preservation.status %></td>
          <td><%= @preservation.initial_file_link %></td>
          <td><%= @preservation.preserved_file_link %></td>
          <td><%= raw @preservation.logs.gsub("\n", "<br>").html_safe %></td>
        </tr>
      </tbody>
  </table>
</div>