config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'

  # Task 1
  resources :orders, only: :index
  get 'last_year', to: 'orders#within_last_year', as: :last_year_orders
  get '/api/last_year_by_months', to: 'api/orders#last_year_by_months', as: :last_year_by_months

  resources :preservations, only: %i[index show new create]
  resources :reports, only: %i[index]
  get '/get_report', to: 'reports#get_report', as: :get_report
end

app/views/shared/_errors.html.erb
<% if object&.errors&.any? %>
  <div class="alert alert-danger">
    <h4>There were problems with your submission:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key == "alert" ? "danger" : "success" %>" role="alert">
    <%= value %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<div class="container container-widest" style="padding-top: 30px;padding-bottom: 0px;">
  <span style="padding-top: 8px;">
    <%= "You are: #{current_user.email}" %>
  </span>
  <span>
    &nbsp;&nbsp;
  </span>
  <span>
    <%= link_to 'All orders', orders_path, class: 'btn btn-primary btn-lg mb-3', style: 'text-align: right', data: { turbo: false } %>
  </span>
  <span>
    &nbsp;&nbsp;
  </span>
  <span>
    <%= link_to 'Last 12 months orders', last_year_orders_path, class: 'btn btn-primary btn-lg mb-3', style: 'text-align: right', data: { turbo: false } %>
  </span>
  <span>
    &nbsp;&nbsp;
  </span>
  <span>
    <%= link_to 'Last 12 months (by months)', last_year_by_months_path, class: 'btn btn-primary btn-lg mb-3', style: 'text-align: right', data: { turbo: false } %>
  </span>
  <span>
    &nbsp;&nbsp;
  </span>
  <span>
    <%= link_to 'Preservations', preservations_path, class: 'btn btn-success btn-lg mb-3', style: 'text-align: right', data: { turbo: false } %>
  </span>
  <span>
    &nbsp;&nbsp;
  </span>
  <span>
    <%= link_to 'Get report', get_report_path, class: 'btn btn-danger btn-lg mb-3', style: 'text-align: right', data: { turbo: false } %>
  </span>
</div>